// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | AboutSlice
  | SkillsSlice
  | ContactSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Navigation Items*
 */
export interface SettingsDocumentDataNavigationItemsItem {
  /**
   * Label field in *Settings → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Home
   * - **API ID Path**: settings.navigationItems[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #home
   * - **API ID Path**: settings.navigationItems[].link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sahin Alom
   * - **API ID Path**: settings.siteName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  siteName: prismic.KeyTextField;

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hello@sahinalom.com
   * - **API ID Path**: settings.contactEmail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contactEmail: prismic.KeyTextField; /**
   * Navigation Items field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigationItems[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigationItems: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationItemsItem>
  >; /**
   * LinkedIn URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn profile
   * - **API ID Path**: settings.linkedinUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedinUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Behance URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Behance profile
   * - **API ID Path**: settings.behanceUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  behanceUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dribbble URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Dribbble profile
   * - **API ID Path**: settings.dribbbleUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dribbbleUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile
   * - **API ID Path**: settings.githubUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  githubUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Instagram profile
   * - **API ID Path**: settings.instagramUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagramUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: © 2026 Sahin Alom. All rights reserved.
   * - **API ID Path**: settings.footerText
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerText: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | SettingsDocument;

/**
 * Item in *About → Default → Primary → Features*
 */
export interface AboutSliceDefaultPrimaryFeaturesItem {
  /**
   * Title field in *About → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SYSTEMIC
   * - **API ID Path**: about.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Scalable design systems...
   * - **API ID Path**: about.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Eyebrow field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: about.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Headline field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Architecting systems...
   * - **API ID Path**: about.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Bio Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bridging the gap...
   * - **API ID Path**: about.default.primary.bioTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bioTitle: prismic.RichTextField;

  /**
   * Description field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bridging the gap...
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Features field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryFeaturesItem>>;

  /**
   * Profile Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: About section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About section with clean typography
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Section Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in Touch
   * - **API ID Path**: contact.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Let's work together...
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Section Image (Wide) field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contactImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  contactImage: prismic.ImageField<never>;

  /**
   * Show Email Button field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showEmailButton
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showEmailButton: prismic.BooleanField;

  /**
   * Show Contact Form field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showContactForm
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showContactForm: prismic.BooleanField;

  /**
   * Show Social Icons field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showSocialIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showSocialIcons: prismic.BooleanField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact section with email button and optional form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: UX • Systems • AI
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sahin Alom
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Headline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: UX Designer with Engineering Systems Thinking
   * - **API ID Path**: hero.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Supporting text...
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in Touch
   * - **API ID Path**: hero.default.primary.primaryCtaLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryCtaLabel: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #contact
   * - **API ID Path**: hero.default.primary.primaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryCtaLink: prismic.KeyTextField;

  /**
   * Secondary CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View LinkedIn
   * - **API ID Path**: hero.default.primary.secondaryCtaLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryCtaLabel: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn URL
   * - **API ID Path**: hero.default.primary.secondaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryCtaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Show Social Icons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero.default.primary.showSocialIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showSocialIcons: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero section for personal portfolio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with animated background, headline, CTAs, and social icons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Section Title field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Skills
   * - **API ID Path**: skills.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Section Intro field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tools and strengths...
   * - **API ID Path**: skills.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Items*
 */
export interface SkillsSliceDefaultItem {
  /**
   * Group Title field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Design
   * - **API ID Path**: skills.items[].groupTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  groupTitle: prismic.KeyTextField;

  /**
   * Skills field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Figma, Sketch, Adobe XD
   * - **API ID Path**: skills.items[].skills
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skills: prismic.KeyTextField;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Skills section with tag groups
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  Simplify<SkillsSliceDefaultItem>
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills section with grouped tags
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItemsItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryFeaturesItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimary,
      SkillsSliceDefaultItem,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
