// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
  | prismic.CustomTypeModelFetchCustomTypeLevel1
  | prismic.CustomTypeModelFetchCustomTypeLevel2
  | prismic.CustomTypeModelFetchGroupLevel1
  | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
    ? prismic.GroupField<
      PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
    >
    : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
  | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
  | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Biodata Page documents
 */
interface BiodataPageDocumentData {
  /**
   * Name field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Full Name
   * - **API ID Path**: biodata_page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Professional Headline field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. UX Designer with Engineering Systems Thinking
   * - **API ID Path**: biodata_page.professional_headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  professional_headline: prismic.KeyTextField;

  /**
   * Summary field in *Biodata Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short professional summary...
   * - **API ID Path**: biodata_page.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Profile Photo field in *Biodata Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.profile_photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profile_photo: prismic.ImageField<never>;

  /**
   * Core Skills field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma separated list, e.g. UX Research, Systems Design, React
   * - **API ID Path**: biodata_page.core_skills
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  core_skills: prismic.KeyTextField;

  /**
   * Education field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. BSc in EEE
   * - **API ID Path**: biodata_page.education
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  education: prismic.KeyTextField;

  /**
   * Work Type field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Freelance / Remote
   * - **API ID Path**: biodata_page.work_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  work_type: prismic.KeyTextField;

  /**
   * Current Focus field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. UX, systems, AI workflows
   * - **API ID Path**: biodata_page.current_focus
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  current_focus: prismic.KeyTextField; /**
   * Show Personal Details field in *Biodata Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: biodata_page.show_personal_details
   * - **Tab**: Personal
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_personal_details: prismic.BooleanField;

  /**
   * Nationality field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Bangladeshi
   * - **API ID Path**: biodata_page.nationality
   * - **Tab**: Personal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nationality: prismic.KeyTextField;

  /**
   * Current Location field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, Country
   * - **API ID Path**: biodata_page.current_location
   * - **Tab**: Personal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  current_location: prismic.KeyTextField;

  /**
   * Languages field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. English, Bengali
   * - **API ID Path**: biodata_page.languages
   * - **Tab**: Personal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  languages: prismic.KeyTextField; /**
   * Show Extended Profile (Marriage/Personal) field in *Biodata Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: biodata_page.show_marriage_section
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_marriage_section: prismic.BooleanField;

  /**
   * Religion field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Islam
   * - **API ID Path**: biodata_page.religion
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  religion: prismic.KeyTextField;

  /**
   * Marital Status field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Single
   * - **API ID Path**: biodata_page.marital_status
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  marital_status: prismic.KeyTextField;

  /**
   * Date of Birth field in *Biodata Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.date_of_birth
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date_of_birth: prismic.DateField;

  /**
   * Height field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 5' 8"
   * - **API ID Path**: biodata_page.height
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  height: prismic.KeyTextField;

  /**
   * Blood Group field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. O+
   * - **API ID Path**: biodata_page.blood_group
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blood_group: prismic.KeyTextField;

  /**
   * Family Information field in *Biodata Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.family_information
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  family_information: prismic.RichTextField;

  /**
   * Partner Preference field in *Biodata Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.partner_preference
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  partner_preference: prismic.RichTextField;

  /**
   * Additional Information field in *Biodata Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.additional_information
   * - **Tab**: Extended Profile
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  additional_information: prismic.RichTextField; /**
   * Professional Contact Email field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hello@example.com
   * - **API ID Path**: biodata_page.contact_email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Show Guardian Contact field in *Biodata Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: biodata_page.show_guardian_contact
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_guardian_contact: prismic.BooleanField;

  /**
   * Guardian Contact Label field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Father's Number
   * - **API ID Path**: biodata_page.guardian_contact_label
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  guardian_contact_label: prismic.KeyTextField;

  /**
   * Guardian Contact Info field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Phone number or email
   * - **API ID Path**: biodata_page.guardian_contact_info
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  guardian_contact_info: prismic.KeyTextField; /**
   * Meta Title field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for SEO
   * - **API ID Path**: biodata_page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Biodata Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for SEO
   * - **API ID Path**: biodata_page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Biodata Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: biodata_page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Biodata Page document from Prismic
 *
 * - **API ID**: `biodata_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BiodataPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BiodataPageDocumentData>,
    "biodata_page",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | AboutSlice
  | SkillsSlice
  | ContactSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type ResumeDocumentDataSlicesSlice =
  | SkillsSlice
  | CertificationSlice
  | EducationSlice
  | ExperienceSlice;

/**
 * Content for Resume documents
 */
interface ResumeDocumentData {
  /**
   * Slice Zone field in *Resume*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ResumeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Resume*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: resume.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Resume*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: resume.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Resume*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Resume document from Prismic
 *
 * - **API ID**: `resume`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResumeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ResumeDocumentData>,
    "resume",
    Lang
  >;

/**
 * Item in *Settings → Navigation Items*
 */
export interface SettingsDocumentDataNavigationItemsItem {
  /**
   * Label field in *Settings → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Home
   * - **API ID Path**: settings.navigationItems[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #home
   * - **API ID Path**: settings.navigationItems[].link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sahin Alom
   * - **API ID Path**: settings.siteName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  siteName: prismic.KeyTextField;

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hello@sahinalom.com
   * - **API ID Path**: settings.contactEmail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contactEmail: prismic.KeyTextField;

  /**
   * Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +1 234 567 890
   * - **API ID Path**: settings.phoneNumber
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phoneNumber: prismic.KeyTextField; /**
   * Navigation Items field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigationItems[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigationItems: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationItemsItem>
  >; /**
   * LinkedIn URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn profile
   * - **API ID Path**: settings.linkedinUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedinUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Behance URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Behance profile
   * - **API ID Path**: settings.behanceUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  behanceUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dribbble URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Dribbble profile
   * - **API ID Path**: settings.dribbbleUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dribbbleUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile
   * - **API ID Path**: settings.githubUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  githubUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Instagram profile
   * - **API ID Path**: settings.instagramUrl
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagramUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: © 2026 Sahin Alom. All rights reserved.
   * - **API ID Path**: settings.footerText
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerText: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BiodataPageDocument
  | HomepageDocument
  | ResumeDocument
  | SettingsDocument
  | BlogPostDocument
  | BlogListingDocument;

/**
 * Item in *About → Default → Primary → Features*
 */
export interface AboutSliceDefaultPrimaryFeaturesItem {
  /**
   * Title field in *About → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SYSTEMIC
   * - **API ID Path**: about.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Scalable design systems...
   * - **API ID Path**: about.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Eyebrow field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: about.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Headline field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Architecting systems...
   * - **API ID Path**: about.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Bio Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bridging the gap...
   * - **API ID Path**: about.default.primary.bioTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bioTitle: prismic.RichTextField;

  /**
   * Description field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bridging the gap...
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Features field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryFeaturesItem>>;

  /**
   * Profile Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: About section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About section with clean typography
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Certification → Default → Primary*
 */
export interface CertificationSliceDefaultPrimary {
  /**
   * Section Title field in *Certification → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Certifications
   * - **API ID Path**: certification.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;
}

/**
 * Primary content in *Certification → Items*
 */
export interface CertificationSliceDefaultItem {
  /**
   * Certificate Name field in *Certification → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: AWS Certified Solutions Architect
   * - **API ID Path**: certification.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Issuer field in *Certification → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Amazon Web Services
   * - **API ID Path**: certification.items[].issuer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  issuer: prismic.KeyTextField;

  /**
   * Date field in *Certification → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2023
   * - **API ID Path**: certification.items[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Issuer Logo field in *Certification → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certification.items[].issuerLogo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  issuerLogo: prismic.ImageField<never>;

  /**
   * Credential URL field in *Certification → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: certification.items[].credentialLink
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  credentialLink: prismic.KeyTextField;
}

/**
 * Default variation for Certification Slice
 *
 * - **API ID**: `default`
 * - **Description**: Certification list
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificationSliceDefaultPrimary>,
  Simplify<CertificationSliceDefaultItem>
>;

/**
 * Slice variation for *Certification*
 */
type CertificationSliceVariation = CertificationSliceDefault;

/**
 * Certification Shared Slice
 *
 * - **API ID**: `certification`
 * - **Description**: Certification section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationSlice = prismic.SharedSlice<
  "certification",
  CertificationSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Section Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in Touch
   * - **API ID Path**: contact.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Email Address field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: you@example.com
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Form Endpoint (Formspree URL) field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://formspree.io/f/your_id
   * - **API ID Path**: contact.default.primary.formEndpoint
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  formEndpoint: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Let's work together...
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Section Image (Wide) field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contactImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  contactImage: prismic.ImageField<never>;

  /**
   * Show Email Button field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showEmailButton
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showEmailButton: prismic.BooleanField;

  /**
   * Show Contact Form field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showContactForm
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showContactForm: prismic.BooleanField;

  /**
   * Show Social Icons field in *Contact → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: contact.default.primary.showSocialIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showSocialIcons: prismic.BooleanField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact section with email button and optional form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Education → Default → Primary*
 */
export interface EducationSliceDefaultPrimary {
  /**
   * Section Title field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Education
   * - **API ID Path**: education.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;
}

/**
 * Primary content in *Education → Items*
 */
export interface EducationSliceDefaultItem {
  /**
   * Degree field in *Education → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: BSc Computer Science
   * - **API ID Path**: education.items[].degree
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  degree: prismic.KeyTextField;

  /**
   * Institution field in *Education → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: University of Technology
   * - **API ID Path**: education.items[].institution
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  institution: prismic.KeyTextField;

  /**
   * Year field in *Education → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2016 - 2020
   * - **API ID Path**: education.items[].year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;

  /**
   * Details field in *Education → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Focus on HCI and Systems...
   * - **API ID Path**: education.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  details: prismic.KeyTextField;
}

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Education list
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EducationSliceDefaultPrimary>,
  Simplify<EducationSliceDefaultItem>
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSlice = prismic.SharedSlice<
  "education",
  EducationSliceVariation
>;

/**
 * Primary content in *Experience → Default → Primary*
 */
export interface ExperienceSliceDefaultPrimary {
  /**
   * Section Title field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Experience
   * - **API ID Path**: experience.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;
}

/**
 * Primary content in *Experience → Items*
 */
export interface ExperienceSliceDefaultItem {
  /**
   * Job Title field in *Experience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Senior UX Designer
   * - **API ID Path**: experience.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Company field in *Experience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Google
   * - **API ID Path**: experience.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Duration field in *Experience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2020 - Present
   * - **API ID Path**: experience.items[].duration
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration: prismic.KeyTextField;

  /**
   * Location field in *Experience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New York, NY
   * - **API ID Path**: experience.items[].location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Description field in *Experience → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe your role...
   * - **API ID Path**: experience.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Skills Used field in *Experience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Figma, React, Systems Thinking
   * - **API ID Path**: experience.items[].skills
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skills: prismic.KeyTextField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Experience list
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSliceDefaultPrimary>,
  Simplify<ExperienceSliceDefaultItem>
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience section with job details
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: UX • Systems • AI
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sahin Alom
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Headline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: UX Designer with Engineering Systems Thinking
   * - **API ID Path**: hero.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Supporting text...
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in Touch
   * - **API ID Path**: hero.default.primary.primaryCtaLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryCtaLabel: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #contact
   * - **API ID Path**: hero.default.primary.primaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryCtaLink: prismic.KeyTextField;

  /**
   * Secondary CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View LinkedIn
   * - **API ID Path**: hero.default.primary.secondaryCtaLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryCtaLabel: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn URL
   * - **API ID Path**: hero.default.primary.secondaryCtaLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryCtaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Show Social Icons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero.default.primary.showSocialIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showSocialIcons: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero section for personal portfolio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with animated background, headline, CTAs, and social icons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Section Title field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Skills
   * - **API ID Path**: skills.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Section Intro field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tools and strengths...
   * - **API ID Path**: skills.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Items*
 */
export interface SkillsSliceDefaultItem {
  /**
   * Group Title field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Design
   * - **API ID Path**: skills.items[].groupTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  groupTitle: prismic.KeyTextField;

  /**
   * Skills field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Figma, Sketch, Adobe XD
   * - **API ID Path**: skills.items[].skills
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skills: prismic.KeyTextField;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Skills section with tag groups
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  Simplify<SkillsSliceDefaultItem>
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills section with grouped tags
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BiodataPageDocument,
      BiodataPageDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ResumeDocument,
      ResumeDocumentData,
      ResumeDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItemsItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryFeaturesItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      CertificationSlice,
      CertificationSliceDefaultPrimary,
      CertificationSliceDefaultItem,
      CertificationSliceVariation,
      CertificationSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      EducationSlice,
      EducationSliceDefaultPrimary,
      EducationSliceDefaultItem,
      EducationSliceVariation,
      EducationSliceDefault,
      ExperienceSlice,
      ExperienceSliceDefaultPrimary,
      ExperienceSliceDefaultItem,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimary,
      SkillsSliceDefaultItem,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;

  /**
   * Category field in *Blog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"Engineering" | "Design" | "Career" | "Systems" | "Personal">;

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short summary...
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Author Name field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Sahin Alom
   * - **API ID Path**: blog_post.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Avatar field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author_avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_avatar: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for Blog Listing documents
 */
interface BlogListingDocumentData {
  /**
   * Title field in *Blog Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog
   * - **API ID Path**: blog_listing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Blog Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Thoughts on engineering...
   * - **API ID Path**: blog_listing.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Meta Title field in *Blog Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Listing document from Prismic
 *
 * - **API ID**: `blog_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogListingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogListingDocumentData>,
    "blog_listing",
    Lang
  >;
export type { BlogPostDocumentData, BlogListingDocumentData };
