// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  about: dynamic(() => import("./About")),
  skills: dynamic(() => import("./Skills")),
  contact: dynamic(() => import("./Contact")),
  experience: dynamic(() => import("./Experience")),
  education: dynamic(() => import("./Education")),
  certification: dynamic(() => import("./Certification")),
};
