/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rtihttzsmkkmzpnlmnlx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0aWh0dHpzbWtrbXpwbmxtbmx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxMDMxODksImV4cCI6MjEwMzY3OTE4OX0.TMjRVRtYpE-rL-GDLMdysTFLSiUdf6G79AL-jiXcoV4"